services:
  postgres:
    image: postgres:16
    shm_size: 1g
    restart: always
    environment:
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_DB
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    command: >
      postgres -c shared_buffers=4GB
               -c work_mem=64MB
               -c maintenance_work_mem=2GB
               -c effective_cache_size=24GB
               -c max_wal_size=8GB
               -c checkpoint_completion_target=0.9
               -c wal_buffers=128MB
               -c max_connections=300
               -c synchronous_commit=off
               -c random_page_cost=1.0
               -c effective_io_concurrency=400
  bitcoind:
    image: fractalbitcoin/fractal:v0.2.1
    restart: always
    entrypoint: ["bitcoind", "-datadir=/data/", "-maxtipage=504576000"]
    command: ""
    healthcheck:
      test: ["CMD", "bitcoin-cli", "-datadir=/data/", "getblockchaininfo"]
    ports:
      - "127.0.0.1:8330:8330"
      - "127.0.0.1:8331:8331"
      - "127.0.0.1:8332:8332"
      - "127.0.0.1:8333:8333"
    deploy:
      resources:
        limits:
          memory: 40G
    memswap_limit: 60G
    mem_swappiness: 100
    volumes:
      - ./docker/data:/data
    logging:
      driver: "json-file"
      options:
        labels: "env,filebeat,name"
        max-size: "1g"
        max-file: "3"
